dataMining/dataMining/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls')),
    path('users/', include('users.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

dataMining/review/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='review-home'),
]

dataMining/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user_main/', views.usermain, name='user-main'),
    # path('user_home/', views.userhome, name='user-home'),
]

dataMining/review/models.py
from django.db import models

class ReviewTab(models.Model):
    rid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, blank=False)
    review_data = models.CharField(max_length=5000, blank=False)
    gender = models.CharField(max_length=25, blank=True)
    rating = models.CharField(max_length=25, blank=True)

dataMining/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    # def __str__(self):
    #     return f'{self.user.username} Profile'

dataMining/review/forms.py
from django import forms
from django.forms import ModelForm
from review.models import *

class ReviewForm(ModelForm):
    class Meta:
        model = ReviewTab
        fields = ['name','review_data']

dataMining/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# class UserHomeForm(forms.Form):
    

dataMining/review/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from review.forms import ReviewForm
from .models import *
from django.contrib import messages

def home(request):
    form = ReviewForm(request.POST)
    if request.method == 'POST':
        # print("request POST")
        if form.is_valid():
            # form.save()
            # print("Validation Success")
            f_name = form.cleaned_data.get('name')
            f_review = form.cleaned_data.get('review_data')
            instance = ReviewTab.objects.create(name=f_name,review_data=f_review)
            instance.save()
            return render(request, 'review/result.html')
        else:
            print(form.errors)
            form = ReviewForm()
    return render(request, 'review/home.html', {'form': form})

dataMining/users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
import sqlite3 as db
import csv
import xlwt, xlrd
from review.models import ReviewTab
from django.http import HttpResponse
from final import _functionTorun

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

def usermain(request):
    if(request.GET.get('mybtn')):
        # print("I am in IF")
        export_to_csv(request)
        _functionTorun()
        wb = xlrd.open_workbook("review.xls")
        sheet = wb.sheet_by_index(0)
        rows = []
        for i in range(1,(sheet.nrows)):
            row = sheet.row_values(i)
            row[0]=int(row[0])
            rows.append(row)
        context = {
            'rows': rows,
        }
        return render(request, 'users/home.html',context)
    else:
        # print("I am in else")
        return render(request, 'users/main.html')

# def userhome(request):
#     if(request.GET.get('mybtn')):
#         print("I am in IF")
#         export_to_csv(request)
#         _functionTorun()
#         wb = xlrd.open_workbook("review.xls")
#         sheet = wb.sheet_by_index(0)
#         rows = []
#         for i in range(1,(sheet.nrows)):
#             row = sheet.row_values(i)
#             row[0]=int(row[0])
#             rows.append(row)
#         context = {
#             'rows': rows,
#         }
#         return render(request, 'users/home.html',context)
#     else:
#         print("I am in else")
#         return render(request, 'users/main.html')

def export_to_csv(request):
    # with open('review.csv', 'w', newline='') as f_handle:
    #     writer = csv.writer(f_handle)
    #     writer.writerow(['ID','name','review','gender','rating'])
    #     r_data = ReviewTab.objects.all().values_list('rid','name','review_data','gender','rating')
    #     for r in r_data:
    #         writer.writerow(r)
    wb = xlwt.Workbook()
    ws = wb.add_sheet('reviews')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['ID','name','review','gender','rating']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)
    font_style = xlwt.XFStyle()
    rows = ReviewTab.objects.all().values_list('rid','name','review_data','gender','rating')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)
    wb.save('review.xls')
    # print("Done creating CSV")

@login_required
def profile(request):
    return render(request, 'users/profile.html')

dataMining/review/templates/review/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <style>
        * {
              box-sizing: border-box;
          }

          .column {
              float: left;
              width: 50%;
              padding: 5px;
          }

          /* Clearfix (clear floats) */
          .row::after {
              content: "";
              clear: both;
              display: table;
          }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        
        th, td {
            text-align: left;
            padding: 8px;
        }
        
        tr:nth-child(even) {background-color: #f2f2f2;}
    </style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'review/main.css' %}">
    <title>Amazon Review Analysis System</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          {% if not user.is_authenticated %}
            <a class="navbar-brand mr-4" href="{% url 'review-home' %}">Amazon Review Analysis System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          {% else %}
            <text class="navbar-brand mr-4">Amazon Review Analysis System</text>
          {% endif %}
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if not user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'review-home' %}">Home</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'user-main' %}">Home</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Retailer Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="center">
          {% block content %}{% endblock %}
      </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

dataMining/review/templates/review/home.html
{% extends "review/base.html" %}
{% block content %}
<div class="content-section">
	<form method="POST">
		{% csrf_token %}
		<fieldset class="form-group">
                <legend class="border-bottom mb-4">Home</legend>
		</fieldset>
		<div id="div_id_username" class="form-group"> 
			<label for="id_username" class="col-form-label  requiredField">
				Reviewer Name<span class="asteriskField">*</span> 
			</label> 
			<div class=""> <input type="text" name="name" autofocus="" maxlength="254" class="textinput textInput form-control" required="" id="id_name"> 
			</div> 
		</div>
		<div id="div_id_username" class="form-group"> 
				<label for="id_username" class="col-form-label  requiredField">
					Review<span class="asteriskField">*</span> 
				</label> 
				<div class=""> <input type="text" name="review_data" autofocus="" maxlength="5000" class="textinput textInput form-control" required="" id="id_review_data"> 
				</div> 
			</div>
		<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Submit</button>
				<button class="btn btn-outline-info" type="clear">Clear</button>
        </div>
		<!-- <div align="center">
			<input type="submit" value="Submit">
			<input type="submit" value="Clear">
		</div> -->
	</form> 
</div>
{% endblock content %}

dataMining/review/templates/review/result.html
{% extends "review/base.html" %}
{% block content %}
<h2>Review Submitted!</h2>
{% endblock content %}

dataMining/users/templates/users/home.html
{% extends "review/base.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4">Graphical view of Results</legend>
    <div class="row">
        <div class="column">
            {% load static %} 
            <img src="{% static 'users/bar.png' %}" alt="Bar Plot" style="width:100%"/>
        </div>
        <div class="column">
            {% load static %} 
            <img src="{% static 'users/pie.png' %}" alt="Pie Chart" style="width:100%"/>
        </div>
    </div>
</div>
<div class="content-section">
    <legend class="border-bottom mb-4">Tabular view of Results</legend>
    <table>
        <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Review</th>
                <th>Gender</th>
                <th>Rating</th>
        </tr>
        {% for row in rows %}
        <tr>
            {% for sub_row in row %}
                <td>{{sub_row}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

dataMining/users/templates/users/login.html
{% extends "review/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

dataMining/users/templates/users/logout.html
{% extends "review/base.html" %}
{% block content %}
    <legend>You have been logged out!</legend>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

dataMining/users/templates/users/main.html
{% extends "review/base.html" %}
{% block content %}
<div class="content-section">
    <legend class="border-bottom mb-4">Welcome to Retailer's View</legend>
    <form action="#" method="get">
        <div class="form-group">
            <input type="submit" class="btn btn-outline-info" value="Run Model" name="mybtn">
            <!-- <button class="btn btn-outline-info" name="mybtn" type="submit">Run</button> -->
        </div>
    </form>
</div>
{% endblock content %}

dataMining/users/templates/users/profile.html
{% extends "review/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="https://specials-images.forbesimg.com/imageserve/55b914f5e4b05c2c343242c1/300x300.jpg?fit=scale&background=000000">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
    </div>
{% endblock content %}

dataMining/users/templates/users/register.html
{% extends "review/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}